apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3scale
resources:
  - ../../bases/threescale-operator
patches:
  - target:
      kind: Subscription
      name: 3scale-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: threescale-2.16
