apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-external
  labels:
    app: system-postgresql-external
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
