apiVersion: v1
kind: Service
metadata:
  name: system-postgresql-service
  labels:
    app: system-postgresql-external
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    deployment: system-postgresql-external
