# Required by ApplicationSet clusterDecisionResource generator.
apiVersion: v1
kind: ConfigMap
metadata:
  name: threescale-external-db-acm-placement
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: threescale-external-db
    app.kubernetes.io/part-of: 3scale
    platform.io/gitops-strategy: acm-push
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  apiVersion: cluster.open-cluster-management.io/v1beta1
  kind: placementdecisions
  matchKey: clusterName
  statusListKey: decisions
