apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops
resources:
  - applicationset-placement-rbac.yaml
  - managedclustersetbinding.yaml
  - placement.yaml
  - acm-placement-configmap.yaml
  - gitopscluster.yaml
  - applicationset-threescale-operator-acm.yaml
