apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: threescale-external-db
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: threescale-external-db
    app.kubernetes.io/part-of: 3scale
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - name: namespace
            path: kustomize/bases/namespace
            wave: "0"
          - name: postgresql
            path: kustomize/bases/postgresql
            wave: "1"
          - name: redis-config
            path: kustomize/bases/redis-config-restore
            wave: "1"
          - name: redis-backend
            path: kustomize/bases/redis-backend
            wave: "2"
          - name: redis-system
            path: kustomize/bases/redis-system
            wave: "2"
  template:
    metadata:
      name: "threescale-ext-{{.name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{.wave}}"
      labels:
        app.kubernetes.io/part-of: 3scale-external-db
    spec:
      project: default
      source:
        repoURL: REPLACE_REPO_URL
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: 3scale-db
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: false
          selfHeal: true
