apiVersion: v1
kind: Service
metadata:
  name: backend-redis-service
  labels:
    app: backend-redis-external
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    deployment: backend-redis-external
